// Lint config for Clio (#365).
//
// The value here is not style. This is a browser extension that scrapes three
// sites' DOM, written as globals-and-module.exports hybrids that run in five
// different environments: content script, popup, service worker, jest/jsdom,
// and plain node for tools/. `no-undef` is the rule that earns its keep --
// it catches a module reaching for a global that exists in one of those
// environments and not another, which is a live failure mode in this codebase
// rather than a theoretical one.
//
// Rules are not disabled to reach zero. Where a rule is relaxed below it is
// relaxed for a stated reason, scoped to the files that need it.
const js = require('@eslint/js');
const globals = require('globals');

// Division of labour, so there is exactly one list of each kind:
//
//   this file          ENVIRONMENT globals -- what the runtime provides
//                      (document, chrome, indexedDB, describe, require).
//   /* global */       PROJECT globals -- what one of our files defines and
//   comments in-file   another reads.
//
// The second kind genuinely exists here. extensions/src/archive.html loads
// lib/jszip.min.js, storage/db.js, enumerate.js, archive.js and
// archive-page.js as classic scripts in that order, so each one's top-level
// declarations are globals to the ones after it; manifest.json pairs the
// selector files with content.js the same way. Those belong next to the file
// that depends on them, where they are read as documentation and where a
// change to archive.html's script order has a visible local consequence.
//
// Keeping both lists in this file was the first attempt and it was wrong: the
// per-file comments then redeclared the central list, 17 no-redeclare errors,
// and the fix for those would have been to delete the more informative copy.

// Helpers tests/setup.js installs on `global` before every suite.
const testHarnessGlobals = {
  loadFixture: 'readonly',
  setFixture: 'readonly',
  TEST_SCROLL_CONFIG: 'readonly',
};

module.exports = [
  {
    ignores: [
      'node_modules/**',
      'extensions/lib/**',      // vendored jszip.min.js -- not ours to lint
      'viewer/viewer.html',     // generated by viewer/build.js
      'data/**',
      'data-dl/**',
      'data-g/**',
    ],
  },

  js.configs.recommended,

  // The one deliberate relaxation in this config, argued rather than assumed.
  //
  // ESLint 9 changed no-unused-vars' default to caughtErrors: 'all', which
  // flags `catch (e) { /* fall through */ }` -- 29 sites here. An unused catch
  // binding is not a defect: the code is handling the failure by ignoring it,
  // which is a decision the binding's presence documents. Turning those into
  // `catch {}` or `_e` across seven files would be churn in service of the
  // linter rather than of the code.
  //
  // Everything the rule is actually worth keeping stays on: unused variables,
  // unused imports and dead functions are still errors, and this pass found
  // four of them in shipped extension code. Underscore-prefixed names are the
  // conventional opt-out for a deliberately ignored argument.
  {
    rules: {
      'no-unused-vars': ['error', {
        args: 'after-used',
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrors: 'none',
      }],
    },
  },

  // Extension code: browser content scripts, popup, service worker. These files
  // also carry the `if (typeof module !== 'undefined' && module.exports)` tail
  // so the same file can be required by jest, hence the commonjs source type
  // and the node globals alongside the browser ones.
  {
    files: ['extensions/src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        ...globals.browser,
        ...globals.webextensions,
        ...globals.commonjs,
      },
    },
  },

  // Viewer: viewer-logic.js runs in the page, build.js is a node script.
  {
    files: ['viewer/viewer-logic.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: { ...globals.browser, ...globals.commonjs },
    },
  },
  {
    files: ['viewer/build.js'],
    languageOptions: { ecmaVersion: 2022, sourceType: 'commonjs', globals: globals.node },
  },

  // Config files: plain node.
  {
    files: ['*.config.js'],
    languageOptions: { ecmaVersion: 2022, sourceType: 'commonjs', globals: globals.node },
  },

  // Tooling: node scripts that SHIP FUNCTIONS INTO THE PAGE. The probes and
  // harvesters under tools/chatgpt/ drive a real browser over CDP, and the
  // bodies they hand to Runtime.evaluate reference document/getComputedStyle
  // legitimately -- that code runs in the page, not in node. Declaring both
  // environments is the accurate description; adding /* global */ comments or
  // disabling no-undef would each be a way of not saying it.
  //
  // The cost is that a genuine typo'd browser global in the node half of one of
  // these files will not be caught. Splitting page code into its own files
  // would fix that and is worth doing if these scripts grow.
  {
    files: ['tools/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      // webextensions because e2e-real-extension.js drives the actual loaded
      // extension and its injected code touches `chrome`.
      globals: { ...globals.node, ...globals.browser, ...globals.webextensions },
    },
  },

  // Unit tests: jest under jsdom, so both browser and node globals are live.
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.jest,
        ...globals.webextensions,
        ...testHarnessGlobals,
      },
    },
  },

  // Playwright specs: node, plus whatever page.evaluate() bodies reference --
  // those run in the browser, not here, so browser globals are legitimate.
  {
    files: ['tests/e2e/**/*.js', 'tests/**/*.e2e.test.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: { ...globals.node, ...globals.browser },
    },
  },
];
